### ISSUE TITLE
When I load your example flow it doesn't work

### ISSUE THREAD

**Issue by Just-another-pleb** [ingeniadevteam/node-red-contrib-ui-week-schedule#1]
The `.json` file you show in your example gives errors because of the comments for each day.
The last line with the `];` the `;` gives an error as well.

With the file and needed modifications for the path, I run the flow and I get a blank template.

![Screenshot from 2019-08-11 09-40-40](https://user-images.githubusercontent.com/39888280/62827860-76d09c80-bc1c-11e9-91ed-a0aec83fbd04.png)

As there are no columns visible with the file loaded, I am guessing "something is missing" but I am at a loss to know what.

Also where do I change the language for the month/day?

The idea looks great, but I am just not getting everything you say about how to use it.

**Comment by vicnala** [comment]
Please see #3
