### ISSUE TITLE
The GUI.   Not the same as in the example.

### ISSUE THREAD

**Issue by Just-another-pleb** [ingeniadevteam/node-red-contrib-ui-week-schedule#3]
On the page the GUI Looks like this:

![Screenshot from 2019-11-21 19-55-04](https://user-images.githubusercontent.com/39888280/69322801-a3736600-0c99-11ea-9e4c-556b8c96d50a.png)

My GUI looks like this:

![Screenshot from 2019-11-21 19-55-11](https://user-images.githubusercontent.com/39888280/69322814-acfcce00-0c99-11ea-8587-8ac23de3499a.png)

There are missing "buttons" in the red area of the first picture on mine.
Also there is the yellow area.    What is that?

I can/will try to make the English names for the things, but I am missing how to create an event.
Sorry.

**Comment by vicnala** [comment]
Hi,

Please try to **set a name** to the node.
It is now set as required field in the configuration of the node (if you upgrade it. See 84580104fd757ae44b3755ca04ed9a5e4b05cba4).
(This is because you can use more than one schedule and every one has to have a different name).

Thanks, Víctor.
