### ISSUE TITLE
Making the text English.   Unable to find where it is in the code

### ISSUE THREAD

**Issue by Just-another-pleb** [ingeniadevteam/node-red-contrib-ui-week-schedule#4]
I have searched the code (best I can) and can't find the week day names (etc) to put them in English.

Weirdly before I named the node, the week days were in English.  (See my other post.)

Now I named the node, they have changed.

As there is config for the node, I am stuck where to look.

**Comment by ouinouin** [comment]
the texts looks like being spread in utils.js, 
do you plan to translate all the strings to english or will you accept a complete translation of the code.
there is also locale files wich looks useles, do you plan to use them in your code ? 
I think your small ui scheduler would gain traction if it was translated in English (i d like also to translate it in french if you accept contribs. Regards.

**Comment by Just-another-pleb** [comment]
Hi,

I think I have bitten off more than I can manage.

You mentioned the utils.js file.

That isn't part of the package is it?   It is else where.
I said I would translate it on the idea that I would find the file in your module.
That would then be an "easy" case of just replacing/adding the required words/names.

I am by no means a programmer.   I just offered to change/translate it to not overload my request of getting help.

Anyway, I shall see if I can find the utils.js file

**Comment by vicnala** [comment]
Hi,

The days are here https://github.com/ingeniadevteam/node-red-contrib-ui-week-schedule/blob/master/utils.js#L411

It would be nice to have a config param to select the language. It's in the TODO list. I'll try to code it when I have some time.

**Comment by Just-another-pleb** [comment]
(This is becoming confusing)

I received this e-mail:

_Víctor Navarro <notifications@github.com> | Víctor Navarro <notifications@github.com> | 25 Nov 2019, 19:02 (13 hours ago)
-- | -- | --
Víctor Navarro <notifications@github.com>

Hi,

The days are here https://github.com/ingeniadevteam/node-red-contrib-ui-week-schedule/blob/master/utils.js#L411_

Note the path:
node-red-contrib-ui/week-schedule.
Unless we are talking about very different nodes, the path where mine is is
node-red-contrib-simple-weekly-scheduler.
The path you mention doesn't exist.

I'm 100% sure I've sent pictures (in previous threads) and you haven't said "This is not my node" so I am taking it as we are both talking about the same node.

That doesn't make sense as in the directory for that node there is no `utils.js` file.

**me@me-desktop:~/.node-red/node_modules/node-red-contrib-simple-weekly-scheduler$ lr
  ----====  Recursive list starts here  ====----
.:
icons    package.json  static            time-filter.js     time-planner.js
LICENSE  README.md     time-filter.html  time-planner.html

./icons:
cal.png

./static:
date.js  index.html  jquery.weekcalendar.css  jquery.weekcalendar.js
me@me-desktop:~/.node-red/node_modules/node-red-contrib-simple-weekly-scheduler$**
